<?php

/**
 * @file
 * Primary module hooks for Opencollective module.
 */

/**
 * Implements hook_theme().
 */
function opencollective_theme() {
  return [
    'opencollective_api_events' => [
      'variables' => [
        'collective_slug' => NULL,
        'events' => [],
      ],
    ],
    'opencollective_api_contributors' => [
      'variables' => [
        'collective_slug' => NULL,
        'contributors' => [],
      ],
    ],
  ];
}

/**
 * Prepares variables for opencollective-api-events template.
 *
 * Default template: opencollective-api-events.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_opencollective_api_events(array &$variables) {
  /** @var \Drupal\oc_graphql_client\Service\GraphQLClient $client */
  $client = \Drupal::service('oc_graphql_client.graphql_client');
  //$client->getCollectiveEvents();
  //dsm($variables, 'here');
  $variables['foo'] = 'bar';
}


/**
 * Prepares variables for opencollective-api-contributors template.
 *
 * Default template: opencollective-api-contributors.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_opencollective_api_contributors(array &$variables) {
  $variables['foo'] = 'bar';
}
