<?php

/**
 * @file
 * Primary module hooks for Opencollective module.
 */

/**
 * Implements hook_theme().
 */
function opencollective_theme() {
  return [
    'opencollective_api_events' => [
      'variables' => [
        'collective_slug' => NULL,
        'events' => [],
      ],
    ],
    'opencollective_api_contributors' => [
      'variables' => [
        'collective_slug' => NULL,
        'contributors' => [],
      ],
    ],
    'opencollective_embed_banner' => [
      'variables' => [
        'collective_slug' => NULL,
      ],
    ],
    'opencollective_embed_button' => [
      'variables' => [
        'collective_slug' => NULL,
        'color' => 'blue',
        'verb' => 'donate'
      ],
    ],
    'opencollective_embed_contribution_flow' => [
      'variables' => [
        'collective_slug' => NULL,
        'tier' => NULL,
      ],
    ],
  ];
}

function template_preprocess_opencollective_embed_banner(&$variables) {
  $variables['attributes']['src'] = "https://opencollective.com/{$variables['collective_slug']}/banner.js";
}

function template_preprocess_opencollective_embed_button(&$variables) {
  // Enforce limited options.
  $colors = ['blue','white'];
  if (!in_array($variables['color'], $colors)) {
    $variables['color'] = $colors[0];
  }

  $verbs = ['donate', 'contribute'];
  if (!in_array($variables['verb'], $verbs)) {
    $variables['verb'] = $verbs[0];
  }

  $variables['attributes']['src'] = "https://opencollective.com/{$variables['collective_slug']}/{$variables['verb']}/button.js";
  $variables['attributes']['color'] = $variables['color'];
}


function template_preprocess_opencollective_embed_contribution_flow(&$variables) {
  // Handle the url difference between default and specific tiers.
  $variables['attributes']['src'] = "https://opencollective.com/embed/{$variables['collective_slug']}/donate";
  if ($variables['tier']) {
    $variables['attributes']['src'] = "https://opencollective.com/embed/{$variables['collective_slug']}/contribute/{$variables['tier']}";
  }
}
